django-multiple-user-types-example/django_school/classroom/urls.py
from django.urls import include, path

from .views import classroom, students, teachers

urlpatterns = [
    path('', classroom.home, name='home'),

    path('students/', include(([
        path('', students.QuizListView.as_view(), name='quiz_list'),
        path('lebel/', students.StudentlebelView.as_view(), name='student_lebel'),
        path('taken/', students.TakenQuizListView.as_view(),
             name='taken_quiz_list'),
        path('retry/', students.RetryQuizListView.as_view(),
             name='retry_quiz_list'),
        path('quiz/<int:pk>/', students.take_quiz, name='take_quiz'),
        path('quiz/<int:pk>/explanation/',
             students.ExplanationListView.as_view(),
             name='quiz_explanation'),
        path('quiz/<int:pk>/explanation/<int:question_pk>/',
             students.ExplanationDetailView.as_view(),
             name='quiz_explanation_detail'),

        path('retry_quiz/<int:pk>/<int:challenge_num>',
             students.retry_quiz, name='retry_quiz'),
    ], 'classroom'), namespace='students')),

    path('teachers/', include(([
        path('', teachers.QuizListView.as_view(), name='quiz_change_list'),
        path('quiz/add/', teachers.QuizCreateView.as_view(), name='quiz_add'),
        path('quiz/<int:pk>/', teachers.QuizUpdateView.as_view(), name='quiz_change'),
        path('quiz/<int:pk>/delete/',
             teachers.QuizDeleteView.as_view(), name='quiz_delete'),
        path('quiz/<int:pk>/results/',
             teachers.QuizResultsView.as_view(), name='quiz_results'),
        path('quiz/<int:pk>/question/add/',
             teachers.question_add, name='question_add'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/',
             teachers.question_change, name='question_change'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/',
             teachers.QuestionDeleteView.as_view(), name='question_delete'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/explanation',
             teachers.ExplanationView.as_view(), name='explanation'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/explanation/delete',
             teachers.ExplanationDeleteView.as_view(), name='explanation_delete'),

    ], 'classroom'), namespace='teachers')),
]

django-multiple-user-types-example/django_school/django_school/urls.py
from django.urls import include, path

from classroom.views import classroom, students, teachers

urlpatterns = [
    path('', include('classroom.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/',
         students.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/',
         teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
]

django-multiple-user-types-example/django_school/classroom/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.core.exceptions import ValidationError

from classroom.models import (Answer, Question, Student, StudentAnswer,
                              Subject, User, Explanation)


class TeacherSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_teacher = True
        if commit:
            user.save()
        return user


class Hoge(forms.CheckboxSelectMultiple):
    template_name = "classroom/students/multiple_input.html"
    option_template_name = "classroom/students/input_option.html"


class StudentSignUpForm(UserCreationForm):
    lebel = forms.ModelMultipleChoiceField(
        queryset=Subject.objects.all(),
        widget=Hoge(attrs={'class': "reset"}),
        required=True
    )

    class Meta(UserCreationForm.Meta):
        model = User

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError(
                self.error_messages["password_mismatch"],
                code="password_mismatch",
            )
        return password2

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.save()
        student = Student.objects.create(user=user)
        student.lebel.add(*self.cleaned_data.get('lebel'))
        return user


class StudentSignUpUnConfirmationPasswordForm(UserCreationForm):
    lebel = forms.ModelMultipleChoiceField(
        queryset=Subject.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "password", "lebel")

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.save()
        student = Student.objects.create(user=user)
        student.lebel.add(*self.cleaned_data.get('lebel'))
        return user

    def clean_password2(self):
        ...  # 確認用パスワードは気にしないことにする


class StudentlebelForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('lebel', )
        widgets = {
            'lebel': forms.CheckboxSelectMultiple
        }


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('text', )


class BaseAnswerInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        super().clean()

        has_one_correct_answer = False
        for form in self.forms:
            if not form.cleaned_data.get('DELETE', False):
                if form.cleaned_data.get('is_correct', False):
                    has_one_correct_answer = True
                    break
        if not has_one_correct_answer:
            raise ValidationError('最低でも答えを1つ選んでください', code='no_correct_answer')


class TakeQuizForm(forms.ModelForm):
    answer = forms.ModelChoiceField(
        queryset=Answer.objects.none(),
        widget=forms.RadioSelect(),
        required=True,
        empty_label=None)

    class Meta:
        model = StudentAnswer
        fields = ('answer', )

    def __init__(self, *args, **kwargs):
        question = kwargs.pop('question')
        order = kwargs.pop('order', 'text')
        super().__init__(*args, **kwargs)
        self.fields['answer'].queryset = question.answers.order_by(order)


class ExplanationForm(forms.ModelForm):
    class Meta:
        model = Explanation
        fields = ('text', )
        labels = {
            'text': '解説文入力',
        }
        widgets = {
            'text': forms.Textarea(attrs={'placeholder': '解説文をここに入力'}),
        }

django-multiple-user-types-example/django_school/classroom/views/teachers.py
from typing import Any
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView, FormView)

from ..decorators import teacher_required
from ..forms import (BaseAnswerInlineFormSet, QuestionForm, TeacherSignUpForm,
                     ExplanationForm)
from ..models import Answer, Question, Quiz, User, Explanation
from ..mixins import TeacherRequiredMixin


class TeacherSignUpView(CreateView):
    model = User
    form_class = TeacherSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'teacher'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('teachers:quiz_change_list')


class QuizListView(TeacherRequiredMixin, ListView):
    model = Quiz
    ordering = ('name', )
    context_object_name = 'quizzes'
    template_name = 'classroom/teachers/quiz_change_list.html'

    def get_queryset(self):
        queryset = self.request.user.quizzes \
            .select_related('subject') \
            .annotate(questions_count=Count('questions', distinct=True)) \
            .annotate(taken_count=Count('taken_quizzes', distinct=True))
        return queryset


class QuizCreateView(TeacherRequiredMixin, CreateView):
    model = Quiz
    fields = ('name', 'subject', )
    template_name = 'classroom/teachers/quiz_add_form.html'

    def form_valid(self, form):
        quiz = form.save(commit=False)
        quiz.owner = self.request.user
        quiz.save()
        messages.success(
            self.request, 'The quiz was created with success! Go ahead and add some questions now.')
        return redirect('teachers:quiz_change', quiz.pk)


class QuizUpdateView(TeacherRequiredMixin, UpdateView):
    model = Quiz
    fields = ('name', 'subject', )
    context_object_name = 'quiz'
    template_name = 'classroom/teachers/quiz_change_form.html'

    def get_context_data(self, **kwargs):
        kwargs['questions'] = self.get_object().questions.annotate(
            answers_count=Count('answers'))
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        '''
        This method is an implicit object-level permission management
        This view will only match the ids of existing quizzes that belongs
        to the logged in user.
        '''
        return self.request.user.quizzes.all()

    def get_success_url(self):
        return reverse('teachers:quiz_change', kwargs={'pk': self.object.pk})


class QuizDeleteView(TeacherRequiredMixin, DeleteView):
    model = Quiz
    context_object_name = 'quiz'
    template_name = 'classroom/teachers/quiz_delete_confirm.html'
    success_url = reverse_lazy('teachers:quiz_change_list')

    def delete(self, request, *args, **kwargs):
        quiz = self.get_object()
        messages.success(
            request, 'The quiz %s was deleted with success!' % quiz.name)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return self.request.user.quizzes.all()


class QuizResultsView(TeacherRequiredMixin, DetailView):
    model = Quiz
    context_object_name = 'quiz'
    template_name = 'classroom/teachers/quiz_results.html'

    def get_context_data(self, **kwargs):
        quiz = self.get_object()
        taken_quizzes = quiz.taken_quizzes.select_related(
            'student__user').order_by('-date')
        total_taken_quizzes = taken_quizzes.count()
        quiz_score = quiz.taken_quizzes.aggregate(average_score=Avg('score'))
        extra_context = {
            'taken_quizzes': taken_quizzes,
            'total_taken_quizzes': total_taken_quizzes,
            'quiz_score': quiz_score
        }
        kwargs.update(extra_context)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return self.request.user.quizzes.all()


@login_required
@teacher_required
def question_add(request, pk):
    # By filtering the quiz by the url keyword argument `pk` and
    # by the owner, which is the logged in user, we are protecting
    # this view at the object-level. Meaning only the owner of
    # quiz will be able to add questions to it.
    quiz = get_object_or_404(Quiz, pk=pk, owner=request.user)

    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.quiz = quiz
            question.save()
            messages.success(request, '問題を追加')
            return redirect('teachers:question_change', quiz.pk, question.pk)
    else:
        form = QuestionForm()

    return render(request, 'classroom/teachers/question_add_form.html', {'quiz': quiz, 'form': form})


@login_required
@teacher_required
def question_change(request, quiz_pk, question_pk):
    # Simlar to the `question_add` view, this view is also managing
    # the permissions at object-level. By querying both `quiz` and
    # `question` we are making sure only the owner of the quiz can
    # change its details and also only questions that belongs to this
    # specific quiz can be changed via this url (in cases where the
    # user might have forged/player with the url params.
    quiz = get_object_or_404(Quiz, pk=quiz_pk, owner=request.user)
    question = get_object_or_404(Question, pk=question_pk, quiz=quiz)

    AnswerFormSet = inlineformset_factory(
        Question,  # parent model
        Answer,  # base model
        formset=BaseAnswerInlineFormSet,
        fields=('text', 'is_correct'),
        min_num=2,
        validate_min=True,
        max_num=10,
        validate_max=True
    )

    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        formset = AnswerFormSet(request.POST, instance=question)
        if form.is_valid() and formset.is_valid():
            with transaction.atomic():
                form.save()
                formset.save()
            messages.success(request, '問題データのセーブ完了！')
            return redirect('teachers:quiz_change', quiz.pk)
    else:
        form = QuestionForm(instance=question)
        formset = AnswerFormSet(instance=question)

    return render(request, 'classroom/teachers/question_change_form.html', {
        'quiz': quiz,
        'question': question,
        'form': form,
        'formset': formset
    })


class QuestionDeleteView(TeacherRequiredMixin, DeleteView):
    model = Question
    context_object_name = 'question'
    template_name = 'classroom/teachers/question_delete_confirm.html'
    pk_url_kwarg = 'question_pk'

    def get_context_data(self, **kwargs):
        question = self.get_object()
        kwargs['quiz'] = question.quiz
        return super().get_context_data(**kwargs)

    def delete(self, request, *args, **kwargs):
        question = self.get_object()
        messages.success(
            request, 'The question %s was deleted with success!' % question.text)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return Question.objects.filter(quiz__owner=self.request.user)

    def get_success_url(self):
        question = self.get_object()
        return reverse('teachers:quiz_change', kwargs={'pk': question.quiz_id})


class ExplanationView(TeacherRequiredMixin, FormView):
    template_name = 'classroom/teachers/explanation_form.html'
    form_class = ExplanationForm

    def _get_question(self) -> Question:
        return Question.objects.get(
            pk=self.kwargs['question_pk'])

    def get_success_url(self):
        question = self._get_question()
        return reverse('teachers:question_change', kwargs={'quiz_pk': question.quiz.pk, 'question_pk': question.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        question = Question.objects.get(
            pk=self.kwargs['question_pk'])
        context['question'] = question

        return context

    def form_valid(self, form):
        explanation = form.save(commit=False)
        if explanation.pk is None:
            explanation.question = self._get_question()
        explanation.save()

        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        question = Question.objects.get(
            pk=self.kwargs['question_pk'])

        # 解説がすでにある場合は、引っ張ってくる
        if hasattr(question, 'explanation'):
            kwargs.update({
                'instance': question.explanation
            })

        return kwargs


class ExplanationDeleteView(TeacherRequiredMixin, DeleteView):
    model = Explanation
    context_object_name = 'explanation'
    template_name = 'classroom/teachers/explanation_delete_confirm.html'
    pk_url_kwarg = 'question_pk'

    def get_object(self, queryset=None):
        question = Question.objects.get(
            pk=self.kwargs['question_pk'])

        if hasattr(question, 'explanation'):
            return question.explanation

        return None

    def get_context_data(self, **kwargs):
        explanation = self.get_object()
        kwargs['quiz'] = explanation.question.quiz
        return super().get_context_data(**kwargs)


django-multiple-user-types-example/django_school/classroom/templates/classroom/students/_header.html
<h1>問題一覧</h1>
<p class="text-muted">
  レベル:{% for subject in user.student.lebel.all %} {{ subject.get_html_badge }}{% endfor %}
  <a href="{% url 'students:student_lebel' %}" class="button-49">(レベル変更)</a>
  <link rel="animation" href="animation.css">
</p>

<ul class="nav nav-tabs mb-3">
  <li class="nav-item">
    <a class="nav-link{% if active == 'new' %} active{% endif %}" href="{% url 'students:quiz_list' %}">New</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if active == 'taken' %} active{% endif %}" href="{% url 'students:taken_quiz_list' %}">完了</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if active == 'retry' %} active{% endif %}" href="{% url 'students:retry_quiz_list' %}">再挑戦</a>
  </li>
</ul>

django-multiple-user-types-example/django_school/classroom/templates/classroom/students/explanations_detail.html
{% extends 'base.html' %}
{% load common_tags %}
{% block content %}
  <div class="card">
    <div class="card-body">
      <div>
        <div class="mb-3">
          <h2>
            問題：
          </h2>
          <div style="margin-left: 1em;">
            {{ explanation.question.text }}
          </div>
        </div>
        <div class="mb-3">
          <h2>
            解答：
          </h2>
          <div>
            <ol>
              {% for answer in explanation.question.answers.all %}
                <li {% if answer.is_correct %}class="correct text-danger"{% endif %}>{{answer}}</li>
              {% endfor %}
            </ol>
          </div>
          <div class="mb-3" style="margin-left: 1em;">
            {% get_latest_answer request.user.student explanation.question as student_answer %}
            あなたの解答： {{ student_answer.answer.text }}
          </div>
        </div>
        <div>
          <h2>
            解説：
          </h2>
          <div class="mx-3">
            {{ explanation.text }}
          </div>
        </div>
      </div>
    </div>
  </div>
  <div>
    <a href="{% url "students:quiz_explanation" explanation.question.quiz.pk %}" class="btn btn-outline-secondary float-right mt-3" role="button" style="margin-left: auto;">戻る</a>
  </div>
  <style>
    li.correct::before {
      content: "○";
      color: red;
      margin-right: 0.5rem;
    }
  </style>
{% endblock %}

django-multiple-user-types-example/django_school/classroom/templates/classroom/students/explanations_list.html
{% extends 'base.html' %}
{% load common_tags %}
{% block content %}
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>問題</th>
          <th>間違え</th>
          <th>設問数</th>
        </tr>
      </thead>
      <tbody>
        {% for question in questions %}
          <tr>
            <td>
              {% if question.explanation %}
                <a href="{% url 'students:quiz_explanation_detail' question.quiz.pk question.pk %}">
                  {{ question.text }}
                </a>
              {% else %}
                {{ question.text }}
              {% endif %}
            </td>
            {% comment "" %}<a href="{% url 'students:quiz_explanation_detail' question.quiz.pk question.pk %}">{% endcomment %}
            <td>
              {% get_latest_answer request.user.student question as answer %}
              {% if not answer.answer.is_correct %}
              <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-check-lg" viewBox="0 0 16 16" style="color: red;">
                <path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z"/>
              </svg>
              {% endif %}
            </td>
            <td>{{ question.answers.count }}</td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="3">クイズを完了していません</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
  <div>
    <a href="{% url 'students:taken_quiz_list' %}" class="btn btn-outline-secondary float-right mt-3" role="button" style="margin-left: auto;">戻る</a>
  </div>
{% endblock %}

django-multiple-user-types-example/django_school/classroom/templates/classroom/students/lebel_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2 class="mb-3">難易度の変更</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">保存</button>
    <a href="{% url 'students:quiz_list' %}" class="btn btn-outline-secondary">戻る</a>
  </form>
{% endblock %}

django-multiple-user-types-example/django_school/classroom/templates/classroom/students/quiz_list.html
{% extends 'base.html' %}

{% block content %}
  {% include 'classroom/students/_header.html' with active='new' %}
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>問題</th>
          <th>レベル</th>
          <th>問題数</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for quiz in quizzes %}
          <tr>
            <td class="align-middle">{{ quiz.name }}</td>
            <td class="align-middle">{{ quiz.subject.get_html_badge }}</td>
            <td class="align-middle">{{ quiz.questions_count }} 問</td>
            <td class="text-right">
              <a href="{% url 'students:take_quiz' quiz.pk %}" class="btn btn-primary">Start</a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="4">できる問題はありません。</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

django-multiple-user-types-example/django_school/classroom/templates/classroom/students/retry_quiz_list.html
{% extends 'base.html' %}

{% block content %}
  {% include 'classroom/students/_header.html' with active='retry' %}
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>問題</th>
          <th>レベル</th>
          <th>問題数</th>
          <th>挑戦回数</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for quiz in retry_quizzes %}
          <tr>
            <td class="align-middle">{{ quiz.name }}</td>
            <td class="align-middle">{% include "classroom/components/subject_badge.html" with color=quiz.subject_color name=quiz.subject_name %}</td>
            <td class="align-middle">{{ quiz.not_corrected_count }} 問</td>
            <td class="align-middle">{{ quiz.try_num }} 回</td>
            <td class="text-right">
              <a href="{% url 'students:retry_quiz' quiz.quiz_id quiz.try_num %}" class="btn btn-primary">Start</a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="4">間違えた問題はありません</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

django-multiple-user-types-example/django_school/classroom/templates/classroom/students/take_quiz_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="progress mb-3">
    <div class="progress-bar" role="progressbar" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress }}%"></div>
  </div>
  <h2 class="mb-3">{{ quiz.name }}</h2>
  <p class="lead">{{ question.text }}</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Next →</button>
  </form>
{% endblock %}