django-multiple-user-types-example/django_school/classroom/urls.py
from django.urls import include, path

from .views import classroom, students, teachers

urlpatterns = [
    path('', classroom.home, name='home'),

    path('students/', include(([
        path('', students.QuizListView.as_view(), name='quiz_list'),
        path('lebel/', students.StudentlebelView.as_view(), name='student_lebel'),
        path('taken/', students.TakenQuizListView.as_view(),
             name='taken_quiz_list'),
        path('retry/', students.RetryQuizListView.as_view(),
             name='retry_quiz_list'),
        path('quiz/<int:pk>/', students.take_quiz, name='take_quiz'),
        path('quiz/<int:pk>/explanation/',
             students.ExplanationListView.as_view(),
             name='quiz_explanation'),
        path('quiz/<int:pk>/explanation/<int:question_pk>/',
             students.ExplanationDetailView.as_view(),
             name='quiz_explanation_detail'),

        path('retry_quiz/<int:pk>/<int:challenge_num>',
             students.retry_quiz, name='retry_quiz'),
    ], 'classroom'), namespace='students')),

    path('teachers/', include(([
        path('', teachers.QuizListView.as_view(), name='quiz_change_list'),
        path('quiz/add/', teachers.QuizCreateView.as_view(), name='quiz_add'),
        path('quiz/<int:pk>/', teachers.QuizUpdateView.as_view(), name='quiz_change'),
        path('quiz/<int:pk>/delete/',
             teachers.QuizDeleteView.as_view(), name='quiz_delete'),
        path('quiz/<int:pk>/results/',
             teachers.QuizResultsView.as_view(), name='quiz_results'),
        path('quiz/<int:pk>/question/add/',
             teachers.question_add, name='question_add'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/',
             teachers.question_change, name='question_change'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/',
             teachers.QuestionDeleteView.as_view(), name='question_delete'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/explanation',
             teachers.ExplanationView.as_view(), name='explanation'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/explanation/delete',
             teachers.ExplanationDeleteView.as_view(), name='explanation_delete'),

    ], 'classroom'), namespace='teachers')),
]

django-multiple-user-types-example/django_school/django_school/urls.py
from django.urls import include, path

from classroom.views import classroom, students, teachers

urlpatterns = [
    path('', include('classroom.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/',
         students.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/',
         teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
]

django-multiple-user-types-example/django_school/classroom/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.core.exceptions import ValidationError

from classroom.models import (Answer, Question, Student, StudentAnswer,
                              Subject, User, Explanation)


class TeacherSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_teacher = True
        if commit:
            user.save()
        return user


class Hoge(forms.CheckboxSelectMultiple):
    template_name = "classroom/students/multiple_input.html"
    option_template_name = "classroom/students/input_option.html"


class StudentSignUpForm(UserCreationForm):
    lebel = forms.ModelMultipleChoiceField(
        queryset=Subject.objects.all(),
        widget=Hoge(attrs={'class': "reset"}),
        required=True
    )

    class Meta(UserCreationForm.Meta):
        model = User

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError(
                self.error_messages["password_mismatch"],
                code="password_mismatch",
            )
        return password2

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.save()
        student = Student.objects.create(user=user)
        student.lebel.add(*self.cleaned_data.get('lebel'))
        return user


class StudentSignUpUnConfirmationPasswordForm(UserCreationForm):
    lebel = forms.ModelMultipleChoiceField(
        queryset=Subject.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "password", "lebel")

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.save()
        student = Student.objects.create(user=user)
        student.lebel.add(*self.cleaned_data.get('lebel'))
        return user

    def clean_password2(self):
        ...  # 確認用パスワードは気にしないことにする


class StudentlebelForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('lebel', )
        widgets = {
            'lebel': forms.CheckboxSelectMultiple
        }


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('text', )


class BaseAnswerInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        super().clean()

        has_one_correct_answer = False
        for form in self.forms:
            if not form.cleaned_data.get('DELETE', False):
                if form.cleaned_data.get('is_correct', False):
                    has_one_correct_answer = True
                    break
        if not has_one_correct_answer:
            raise ValidationError('最低でも答えを1つ選んでください', code='no_correct_answer')


class TakeQuizForm(forms.ModelForm):
    answer = forms.ModelChoiceField(
        queryset=Answer.objects.none(),
        widget=forms.RadioSelect(),
        required=True,
        empty_label=None)

    class Meta:
        model = StudentAnswer
        fields = ('answer', )

    def __init__(self, *args, **kwargs):
        question = kwargs.pop('question')
        order = kwargs.pop('order', 'text')
        super().__init__(*args, **kwargs)
        self.fields['answer'].queryset = question.answers.order_by(order)


class ExplanationForm(forms.ModelForm):
    class Meta:
        model = Explanation
        fields = ('text', )
        labels = {
            'text': '解説文入力',
        }
        widgets = {
            'text': forms.Textarea(attrs={'placeholder': '解説文をここに入力'}),
        }

django-multiple-user-types-example/django_school/classroom/views/teachers.py
from typing import Any
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView, FormView)

from ..decorators import teacher_required
from ..forms import (BaseAnswerInlineFormSet, QuestionForm, TeacherSignUpForm,
                     ExplanationForm)
from ..models import Answer, Question, Quiz, User, Explanation
from ..mixins import TeacherRequiredMixin


class TeacherSignUpView(CreateView):
    model = User
    form_class = TeacherSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'teacher'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('teachers:quiz_change_list')


class QuizListView(TeacherRequiredMixin, ListView):
    model = Quiz
    ordering = ('name', )
    context_object_name = 'quizzes'
    template_name = 'classroom/teachers/quiz_change_list.html'

    def get_queryset(self):
        queryset = self.request.user.quizzes \
            .select_related('subject') \
            .annotate(questions_count=Count('questions', distinct=True)) \
            .annotate(taken_count=Count('taken_quizzes', distinct=True))
        return queryset


class QuizCreateView(TeacherRequiredMixin, CreateView):
    model = Quiz
    fields = ('name', 'subject', )
    template_name = 'classroom/teachers/quiz_add_form.html'

    def form_valid(self, form):
        quiz = form.save(commit=False)
        quiz.owner = self.request.user
        quiz.save()
        messages.success(
            self.request, 'The quiz was created with success! Go ahead and add some questions now.')
        return redirect('teachers:quiz_change', quiz.pk)


class QuizUpdateView(TeacherRequiredMixin, UpdateView):
    model = Quiz
    fields = ('name', 'subject', )
    context_object_name = 'quiz'
    template_name = 'classroom/teachers/quiz_change_form.html'

    def get_context_data(self, **kwargs):
        kwargs['questions'] = self.get_object().questions.annotate(
            answers_count=Count('answers'))
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        '''
        This method is an implicit object-level permission management
        This view will only match the ids of existing quizzes that belongs
        to the logged in user.
        '''
        return self.request.user.quizzes.all()

    def get_success_url(self):
        return reverse('teachers:quiz_change', kwargs={'pk': self.object.pk})


class QuizDeleteView(TeacherRequiredMixin, DeleteView):
    model = Quiz
    context_object_name = 'quiz'
    template_name = 'classroom/teachers/quiz_delete_confirm.html'
    success_url = reverse_lazy('teachers:quiz_change_list')

    def delete(self, request, *args, **kwargs):
        quiz = self.get_object()
        messages.success(
            request, 'The quiz %s was deleted with success!' % quiz.name)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return self.request.user.quizzes.all()


class QuizResultsView(TeacherRequiredMixin, DetailView):
    model = Quiz
    context_object_name = 'quiz'
    template_name = 'classroom/teachers/quiz_results.html'

    def get_context_data(self, **kwargs):
        quiz = self.get_object()
        taken_quizzes = quiz.taken_quizzes.select_related(
            'student__user').order_by('-date')
        total_taken_quizzes = taken_quizzes.count()
        quiz_score = quiz.taken_quizzes.aggregate(average_score=Avg('score'))
        extra_context = {
            'taken_quizzes': taken_quizzes,
            'total_taken_quizzes': total_taken_quizzes,
            'quiz_score': quiz_score
        }
        kwargs.update(extra_context)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return self.request.user.quizzes.all()


@login_required
@teacher_required
def question_add(request, pk):
    # By filtering the quiz by the url keyword argument `pk` and
    # by the owner, which is the logged in user, we are protecting
    # this view at the object-level. Meaning only the owner of
    # quiz will be able to add questions to it.
    quiz = get_object_or_404(Quiz, pk=pk, owner=request.user)

    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.quiz = quiz
            question.save()
            messages.success(request, '問題を追加')
            return redirect('teachers:question_change', quiz.pk, question.pk)
    else:
        form = QuestionForm()

    return render(request, 'classroom/teachers/question_add_form.html', {'quiz': quiz, 'form': form})


@login_required
@teacher_required
def question_change(request, quiz_pk, question_pk):
    # Simlar to the `question_add` view, this view is also managing
    # the permissions at object-level. By querying both `quiz` and
    # `question` we are making sure only the owner of the quiz can
    # change its details and also only questions that belongs to this
    # specific quiz can be changed via this url (in cases where the
    # user might have forged/player with the url params.
    quiz = get_object_or_404(Quiz, pk=quiz_pk, owner=request.user)
    question = get_object_or_404(Question, pk=question_pk, quiz=quiz)

    AnswerFormSet = inlineformset_factory(
        Question,  # parent model
        Answer,  # base model
        formset=BaseAnswerInlineFormSet,
        fields=('text', 'is_correct'),
        min_num=2,
        validate_min=True,
        max_num=10,
        validate_max=True
    )

    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        formset = AnswerFormSet(request.POST, instance=question)
        if form.is_valid() and formset.is_valid():
            with transaction.atomic():
                form.save()
                formset.save()
            messages.success(request, '問題データのセーブ完了！')
            return redirect('teachers:quiz_change', quiz.pk)
    else:
        form = QuestionForm(instance=question)
        formset = AnswerFormSet(instance=question)

    return render(request, 'classroom/teachers/question_change_form.html', {
        'quiz': quiz,
        'question': question,
        'form': form,
        'formset': formset
    })


class QuestionDeleteView(TeacherRequiredMixin, DeleteView):
    model = Question
    context_object_name = 'question'
    template_name = 'classroom/teachers/question_delete_confirm.html'
    pk_url_kwarg = 'question_pk'

    def get_context_data(self, **kwargs):
        question = self.get_object()
        kwargs['quiz'] = question.quiz
        return super().get_context_data(**kwargs)

    def delete(self, request, *args, **kwargs):
        question = self.get_object()
        messages.success(
            request, 'The question %s was deleted with success!' % question.text)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return Question.objects.filter(quiz__owner=self.request.user)

    def get_success_url(self):
        question = self.get_object()
        return reverse('teachers:quiz_change', kwargs={'pk': question.quiz_id})


class ExplanationView(TeacherRequiredMixin, FormView):
    template_name = 'classroom/teachers/explanation_form.html'
    form_class = ExplanationForm

    def _get_question(self) -> Question:
        return Question.objects.get(
            pk=self.kwargs['question_pk'])

    def get_success_url(self):
        question = self._get_question()
        return reverse('teachers:question_change', kwargs={'quiz_pk': question.quiz.pk, 'question_pk': question.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        question = Question.objects.get(
            pk=self.kwargs['question_pk'])
        context['question'] = question

        return context

    def form_valid(self, form):
        explanation = form.save(commit=False)
        if explanation.pk is None:
            explanation.question = self._get_question()
        explanation.save()

        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        question = Question.objects.get(
            pk=self.kwargs['question_pk'])

        # 解説がすでにある場合は、引っ張ってくる
        if hasattr(question, 'explanation'):
            kwargs.update({
                'instance': question.explanation
            })

        return kwargs


class ExplanationDeleteView(TeacherRequiredMixin, DeleteView):
    model = Explanation
    context_object_name = 'explanation'
    template_name = 'classroom/teachers/explanation_delete_confirm.html'
    pk_url_kwarg = 'question_pk'

    def get_object(self, queryset=None):
        question = Question.objects.get(
            pk=self.kwargs['question_pk'])

        if hasattr(question, 'explanation'):
            return question.explanation

        return None

    def get_context_data(self, **kwargs):
        explanation = self.get_object()
        kwargs['quiz'] = explanation.question.quiz
        return super().get_context_data(**kwargs)


django-multiple-user-types-example/django_school/classroom/templates/classroom/teachers/explanation_delete_confirm.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">問題作成データ</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ explanation.question.quiz.name }}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:question_change' explanation.question.quiz.pk explanation.question.pk %}">{{ explanation.question.text|slice:5 }}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:explanation' explanation.question.quiz.pk explanation.question.pk %}">解説</a></li>
      <li class="breadcrumb-item active" aria-current="page">削除の確認</li>
    </ol>
  </nav>
  <h2 class="mb-3">削除の確認</h2>
  <p class="lead"><div>解説文：<strong>"{{ explanation.text }}"</strong></div>を削除してもよろしいですか? 元に戻ることはありません。</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-lg">Yes, I'm sure</button>
    <a href="{% url 'teachers:explanation' explanation.question.quiz.pk explanation.question.pk %}" class="btn btn-outline-secondary btn-lg" role="button">キャンセル</a>
  </form>
{% endblock %}

django-multiple-user-types-example/django_school/classroom/templates/classroom/teachers/explanation_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">問題一覧</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' question.quiz.pk %}">{{ question.quiz.name }}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:question_change' question.quiz.pk question.pk %}">{{ question|slice:5 }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">問題の新規作成</li>
    </ol>
  </nav>
  <h2 class="mb-3">解説入力</h2>
  <p class="lead"><div style="font-size: 0.8rem;">Question*</div>{{ question.text }}</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">保存</button>
    <a href="{% url 'teachers:question_change' question.quiz.pk question.pk %}" class="btn btn-outline-secondary" role="button">戻る</a>

    {% comment "" %}インタンスがある場合のみ削除可能とする{% endcomment %}
    {% if form.instance.pk %}
      <a href="{% url "teachers:explanation_delete" question.quiz.pk question.pk %}" class="btn btn-danger float-right">消去</a>
    {% endif %}
  </form>
{% endblock %}

django-multiple-user-types-example/django_school/classroom/templates/classroom/teachers/question_add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">問題一覧</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">問題の新規作成</li>
    </ol>
  </nav>
  <h2 class="mb-3">問題の追加</h2>
  <p class="lead">最初に質問のテキストを追加します。<br>次に、回答を追加することができます。</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">保存</button>
    <a href="{% url 'teachers:quiz_change' quiz.pk %}" class="btn btn-outline-secondary" role="button">戻る</a>
  </form>
{% endblock %}

django-multiple-user-types-example/django_school/classroom/templates/classroom/teachers/question_change_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags crispy_forms_filters %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">問題一覧</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ question.text }}</li>
    </ol>
  </nav>
  <h2 class="mb-3">{{ question.txt }}</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ formset.management_form }}
    {{ form|crispy }}
    <div class="card mb-3{% if formset.errors %} border-danger{% endif %}">
      <div class="card-header">
        <div class="row">
          <div class="col-8">
            <strong>答え</strong>
          </div>
          <div class="col-2">
            <strong>正解</strong>
          </div>
          <div class="col-2">
            <strong>消去</strong>
          </div>
        </div>
      </div>
      {% for error in formset.non_form_errors %}
        <div class="card-body bg-danger border-danger text-white py-2">{{ error }}</div>
      {% endfor %}
      <div class="list-group list-group-flush list-group-formset">
        {% for form in formset %}
          <div class="list-group-item">
            <div class="row">
              <div class="col-8">
                {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                {{ form.text|as_crispy_field }}
                {% if form.instance.pk and form.text.value != form.instance.text %}<p class="mb-0 mt-1"><small class="text-muted font-italic"><strong>Old answer:</strong> {{ form.instance.text }}</small></p>{% endif %}
              </div>
              <div class="col-2">
                {{ form.is_correct }}
              </div>
              <div class="col-2">
                {% if form.instance.pk %}
                  {{ form.DELETE }}
                {% endif %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
    <p>
    </p>
    <button type="submit" class="btn btn-success">完了</button>
    {% if question.pk %}
      <a href="{% url 'teachers:explanation' quiz.pk question.pk %}" class="btn btn-primary" role="button">解説</a>
    {% endif %}
    <a href="{% url 'teachers:quiz_change' quiz.pk %}" class="btn btn-outline-secondary" role="button">戻る</a>
    <a href="{% url 'teachers:question_delete' quiz.pk question.pk %}" class="btn btn-danger float-right">消去</a>
  </form>
{% endblock %}

django-multiple-user-types-example/django_school/classroom/templates/classroom/teachers/question_delete_confirm.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">問題作成データ</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:question_change' quiz.pk question.pk %}">{{ question.text }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">削除の確認</li>
    </ol>
  </nav>
  <h2 class="mb-3">削除の確認</h2>
  <p class="lead">削除してもよろしいですか<strong>"{{ question.text }}"</strong>? 元に戻ることはありません。</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-lg">Yes, I'm sure</button>
    <a href="{% url 'teachers:question_change' quiz.pk question.pk %}" class="btn btn-outline-secondary btn-lg" role="button">キャンセル</a>
  </form>
{% endblock %}

django-multiple-user-types-example/django_school/classroom/templates/classroom/teachers/quiz_change_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">問題作成データ</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ quiz.name }}</li>
    </ol>
  </nav>
  <h2 class="mb-3">
    {{ quiz.name }}
    <a href="{% url 'teachers:quiz_results' quiz.pk %}" class="btn btn-primary float-right">解答者データ</a>
  </h2>
  <div class="row mb-3">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">保存</button>
        <a href="{% url 'teachers:quiz_change_list' %}" class="btn btn-outline-secondary" role="button">キャンセル</a>
        <a href="{% url 'teachers:quiz_delete' quiz.pk %}" class="btn btn-danger float-right">消去</a>
      </form>
    </div>
  </div>
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col-7">
          <strong>問題</strong>
        </div>
        <div class="col-3">
          <strong>解説</strong>
        </div>
        <div class="col-2">
          <strong>設問数</strong>
        </div>
      </div>
    </div>
    <div class="list-group list-group-flush list-group-formset">
      {% for question in questions %}
        <div class="list-group-item">
          <div class="row">
            <div class="col-7">
              <a href="{% url 'teachers:question_change' quiz.pk question.pk %}">{{ question.text }}</a>
            </div>
            <div class="col-3">
              {% if question.explanation %}
                ○
              {% else %}
                ✕
              {% endif %}
            </div>
            <div class="col-2">
              {{ question.answers_count }}
            </div>
          </div>
        </div>
      {% empty %}
        <div class="list-group-item text-center">
          <p class="text-muted font-italic mb-0">まだ問題は作成されていません。</p>
        </div>
      {% endfor %}
    </div>
    <div class="card-footer">
      <a href="{% url 'teachers:question_add' quiz.pk %}" class="btn btn-primary btn-sm">問題の追加</a>
    </div>
  </div>
{% endblock %}

django-multiple-user-types-example/django_school/classroom/templates/classroom/teachers/quiz_change_list.html
{% extends 'base.html' %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">ホーム</li>
    </ol>
  </nav>
  <h2 class="mb-3">問題一覧</h2>
  <a href="{% url 'teachers:quiz_add' %}" class="btn btn-primary mb-3" role="button">作成！！</a>
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>内容</th>
          <th>難易度</th>
          <th>問題数</th>
          <th>結果</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for quiz in quizzes %}
          <tr>
            <td class="align-middle"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></td>
            <td class="align-middle">{{ quiz.subject.get_html_badge }}</td>
            <td class="align-middle">{{ quiz.questions_count }}</td>
            <td class="align-middle">{{ quiz.taken_count }}</td>
            <td class="text-right">
              <a href="{% url 'teachers:quiz_results' quiz.pk %}" class="btn btn-primary">一覧</a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="5">問題はまだ作成されていません</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}